CELT_HEAD = \
opus/celt/arch.h \
opus/celt/bands.h \
opus/celt/celt.h \
opus/celt/cpu_support.h \
opus/include/opus_types.h \
opus/include/opus_defines.h \
opus/include/opus_custom.h \
opus/celt/cwrs.h \
opus/celt/ecintrin.h \
opus/celt/entcode.h \
opus/celt/entdec.h \
opus/celt/entenc.h \
opus/celt/fixed_debug.h \
opus/celt/fixed_generic.h \
opus/celt/float_cast.h \
opus/celt/_kiss_fft_guts.h \
opus/celt/kiss_fft.h \
opus/celt/laplace.h \
opus/celt/mathops.h \
opus/celt/mdct.h \
opus/celt/mfrngcod.h \
opus/celt/modes.h \
opus/celt/os_support.h \
opus/celt/pitch.h \
opus/celt/celt_lpc.h \
opus/celt/x86/celt_lpc_sse.h \
opus/celt/quant_bands.h \
opus/celt/rate.h \
opus/celt/stack_alloc.h \
opus/celt/vq.h \
opus/celt/static_modes_float.h \
opus/celt/static_modes_fixed.h \
opus/celt/static_modes_float_arm_ne10.h \
opus/celt/static_modes_fixed_arm_ne10.h \
opus/celt/arm/armcpu.h \
opus/celt/arm/fixed_armv4.h \
opus/celt/arm/fixed_armv5e.h \
opus/celt/arm/fixed_arm64.h \
opus/celt/arm/kiss_fft_armv4.h \
opus/celt/arm/kiss_fft_armv5e.h \
opus/celt/arm/pitch_arm.h \
opus/celt/arm/fft_arm.h \
opus/celt/arm/mdct_arm.h \
opus/celt/mips/celt_mipsr1.h \
opus/celt/mips/fixed_generic_mipsr1.h \
opus/celt/mips/kiss_fft_mipsr1.h \
opus/celt/mips/mdct_mipsr1.h \
opus/celt/mips/pitch_mipsr1.h \
opus/celt/mips/vq_mipsr1.h \
opus/celt/x86/pitch_sse.h \
opus/celt/x86/vq_sse.h \
opus/celt/x86/x86cpu.h